server:
  port: 9090

spring:
  application:
    name: admin-server

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

boot:
  admin:
    notify:
      mail:
        enabled: true
        from: your_email@gmail.com
        to: your_email@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false
